resources:
- repo: self
queue:
  name: Hosted VS2017
steps:
- powershell: |
   $tools="$env:build_sourcesdirectory\Packer"
   Write-Host $tools
   Write-Host "##vso[task.setvariable variable=PATH;]${env:PATH};${tools}";
  displayName: 'Set Packer Env Variable'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(System.DefaultWorkingDirectory)'
  inputs:
    SourceFolder: .

    Contents: setup.ps1

    TargetFolder: '$(System.DefaultWorkingDirectory)'

- task: PackerBuild@1
  displayName: 'Build immutable image'
  inputs:
    templateType: custom

    customTemplateLocation: windows.json

    customTemplateParameters: '{"client_id":"$(client_id)","client_secret":"$(client_secret)","tenant_id":"$(tenant_id)","subscription_id":"$(subscription_id)","managed_image_prefix":"$(managed_image_prefix)","managed_image_resource_group_name":"$(managed_image_resource_group_name)"}'

    imageUri: '$imageURL'


